INSERT INTO users (id, email, password, full_name, username, role_id)  VALUES(1, 'example1@example.com', '$2a$04$AqM0bgu8.YGSY2jRbcIckOI2FMwSavsiVd.jHgrx3jIF5lcpsG1xK', 'Oláh Lajos', 'Abdys', 1);
INSERT INTO users (id, email, password, full_name, username, role_id)  VALUES(2, 'example2@example.com', '$2a$04$AqM0bgu8.YGSY2jRbcIckOI2FMwSavsiVd.jHgrx3jIF5lcpsG1xK', 'Hajdu Benedek', 'beni', 2);
INSERT INTO users (id, email, password, full_name, username, role_id)  VALUES(3, 'example3@example.com', '$2a$04$AqM0bgu8.YGSY2jRbcIckOI2FMwSavsiVd.jHgrx3jIF5lcpsG1xK', 'Csoltkó András', 'bandi', 3);
INSERT INTO users (id, email, password, full_name, username, role_id)  VALUES(4, 'example4@example.com', '$2a$04$AqM0bgu8.YGSY2jRbcIckOI2FMwSavsiVd.jHgrx3jIF5lcpsG1xK', 'Tejes László', 'laci', 4);
INSERT INTO users (id, email, password, full_name, username, role_id)  VALUES(5, 'example5@example.com', '$2a$04$AqM0bgu8.YGSY2jRbcIckOI2FMwSavsiVd.jHgrx3jIF5lcpsG1xK', 'Admin Admin', 'admin', 5);

INSERT INTO roles (id, role) VALUES(1, 'ROLE_HRVEZETO');
INSERT INTO roles (id, role) VALUES(2, 'ROLE_HRMUNKATARS');
INSERT INTO roles (id, role) VALUES(3, 'ROLE_SZAKMAIVEZETO');
INSERT INTO roles (id, role) VALUES(4, 'ROLE_SZAKMAIMUNKATARS');
INSERT INTO roles (id, role) values(5,'ROLE_ADMIN');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (1, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (2, 'example1@example.com', 'Example1 Example', 'Mérnök', b'0', 'Junior', 'Budapest');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (3, 'example2@example.com', 'Example2 Example', 'Programozó', b'1', 'Senior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (4, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (5, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (6, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (7, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (8, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (9, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (10, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (11, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (12, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (13, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (14, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (15, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (16, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (17, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (18, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (19, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (20, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (21, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (22, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (23, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO `jeloltek` (`id`, `email`, `full_name`, `poz_nev`, `statusz`, `szint`, `telephely`) VALUES (24, 'example@example.com', 'Example Example', 'Programozó', b'1', 'Junior', 'Debrecen');
INSERT INTO job_type (id, name) VALUES(1, 'Szoftverfejlesztő');
INSERT INTO job_level (id, level) VALUES(1, 'Junior');
INSERT INTO location (id, city) VALUES(1, 'Debrecen');
ALTER TABLE `users` CHANGE `role_id` `role_id` BIGINT(20) NULL DEFAULT NULL;